from pathlib import Path
p=Path('/mnt/data/_v08')
html=(p/'index.html').read_text(encoding='utf-8')
css=(p/'styles.css').read_text(encoding='utf-8')
js=(p/'app.js').read_text(encoding='utf-8')

html=html.replace('<title>TOTK Companion v0.7 DE</title>','<title>TOTK Companion v0.8 DE</title>')
html=html.replace('Hyrule-Begleiter · v0.7 DE','Hyrule-Begleiter · v0.8 DE')
html=html.replace('''          <label class="toggle-row feature-toggle">\n            <input id="hideCompleted" type="checkbox" />\n            <span class="toggle-ui"></span>\n            <span>Erledigte ausblenden</span>\n          </label>''','''          <div class="feature-toggle-group">\n            <label class="toggle-row feature-toggle">\n              <input id="hideCompleted" type="checkbox" />\n              <span class="toggle-ui"></span>\n              <span>Erledigte ausblenden</span>\n            </label>\n            <label class="toggle-row feature-toggle">\n              <input id="showPlaceLabels" type="checkbox" checked />\n              <span class="toggle-ui"></span>\n              <span>Ortsnamen auf der Karte</span>\n            </label>\n          </div>''')
html=html.replace('<img id="mapImage" class="map-image" src="assets/maps/surface-medium.png" draggable="false" alt="TOTK-Karte der Oberfläche" />\n            <div id="markerLayer"></div>', '<img id="mapImage" class="map-image" src="assets/maps/surface-medium.png" draggable="false" alt="TOTK-Karte der Oberfläche" />\n            <div id="placeLabelLayer" aria-hidden="false"></div>\n            <div id="markerLayer"></div>')

# CSS: widen sidebar a bit, filter list one column and wrapping labels, place labels
css=css.replace('--sidebar:292px;','--sidebar:326px;')
css=css.replace('.filter-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}', '.filter-grid{display:grid;grid-template-columns:1fr;gap:5px}')
old='.filter-chip{position:relative;display:grid;grid-template-columns:28px minmax(0,1fr);align-items:center;gap:7px;min-height:42px;padding:6px 8px;'
new='.filter-chip{position:relative;display:grid;grid-template-columns:30px minmax(0,1fr) auto;align-items:center;gap:8px;min-height:40px;padding:6px 9px;'
css=css.replace(old,new)
css=css.replace('.filter-copy b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#d7e4df;font-size:10px;font-weight:700}.filter-copy small{display:block;margin-top:1px;color:#668078;font-size:9px}', '.filter-copy{min-width:0}.filter-copy b{display:block;white-space:normal;overflow-wrap:anywhere;color:#d7e4df;font-size:10px;font-weight:750;line-height:1.18}.filter-copy small{display:block;margin-top:2px;color:#668078;font-size:9px;white-space:nowrap}')
css=css.replace('.feature-toggle{margin:0 0 9px;padding:8px 9px;', '.feature-toggle-group{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:0 0 9px}.feature-toggle{margin:0;padding:8px 9px;min-width:0;')
# add label styles before markerLayer rule
needle='#markerLayer{position:absolute;inset:0;z-index:3}'
labels='''#placeLabelLayer{position:absolute;inset:0;z-index:2;pointer-events:none}\n.place-label{position:absolute;max-width:180px;padding:2px 5px;border-radius:4px;background:rgba(6,12,10,.48);color:rgba(246,250,241,.94);font-size:10px;font-weight:750;line-height:1.15;letter-spacing:.01em;text-align:center;text-shadow:0 1px 3px #000,0 0 4px #000;box-shadow:0 1px 4px rgba(0,0,0,.12);transform:translate(-50%,-50%) scale(var(--invZoom));transform-origin:center;white-space:normal;pointer-events:auto;cursor:pointer;backdrop-filter:blur(1.5px);border:1px solid rgba(255,255,255,.06)}\n.place-label:hover{z-index:9;background:rgba(7,16,13,.84);color:#fff;border-color:rgba(201,255,231,.35)}\n.place-label.major{font-size:11px;font-weight:900;background:rgba(6,12,10,.58);color:#f8fff7}\n'''+needle
css=css.replace(needle,labels)
# Mobile tweaks
css=css.replace('.sidebar{width:92vw;padding:12px 12px 9px}.filter-grid{gap:5px}', '.sidebar{width:min(94vw,360px);padding:12px 12px 9px}.filter-grid{gap:5px}.feature-toggle-group{grid-template-columns:1fr}.filter-chip{grid-template-columns:30px minmax(0,1fr) auto}')
# short-height sidebar width
css=css.replace(':root{--sidebar:278px;--topbar:52px}', ':root{--sidebar:310px;--topbar:52px}')

# JS refs
js=js.replace("const mapViewport=$('mapViewport'),mapWorld=$('mapWorld'),mapImage=$('mapImage'),markerLayer=$('markerLayer'),detailPanel=$('detailPanel'),filters=$('filters'),searchInput=$('searchInput'),hideCompleted=$('hideCompleted');", "const mapViewport=$('mapViewport'),mapWorld=$('mapWorld'),mapImage=$('mapImage'),markerLayer=$('markerLayer'),placeLabelLayer=$('placeLabelLayer'),detailPanel=$('detailPanel'),filters=$('filters'),searchInput=$('searchInput'),hideCompleted=$('hideCompleted'),showPlaceLabels=$('showPlaceLabels');")
js=js.replace("let importedMarkers=load('totk.importedMarkers',[]),customMarkers=load('totk.customMarkers',[]),completed=new Set(load('totk.completed',[])),enabledTypes=new Set(Object.keys(typeInfo));", "let importedMarkers=load('totk.importedMarkers',[]),customMarkers=load('totk.customMarkers',[]),completed=new Set(load('totk.completed',[])),enabledTypes=new Set(Object.keys(typeInfo));\nshowPlaceLabels.checked=load('totk.showPlaceLabels',true)!==false;")
# applyView schedules labels
js=js.replace("$('zoomLevel').textContent=Math.round(view.zoom*100)+'%';\n}", "$('zoomLevel').textContent=Math.round(view.zoom*100)+'%';\n  schedulePlaceLabels();\n}")

# render filters markup count as separate element
js=js.replace("l.innerHTML=`<input type=\"checkbox\" ${enabledTypes.has(k)?'checked':''} data-type=\"${k}\"><span class=\"filter-icon\">${v.icon}</span><span class=\"filter-copy\"><b>${v.label}</b><small>${count.toLocaleString('de-DE')} Marker</small></span>`;", "l.innerHTML=`<input type=\"checkbox\" ${enabledTypes.has(k)?'checked':''} data-type=\"${k}\"><span class=\"filter-icon\">${v.icon}</span><span class=\"filter-copy\"><b>${v.label}</b></span><small class=\"filter-count\">${count.toLocaleString('de-DE')}</small>`;")
# Add CSS filter count via append
css += "\n.filter-count{color:#668078;font-size:9px;white-space:nowrap;text-align:right;align-self:center}\n"

# Insert place label functions before renderMarkers
insert='''\nlet placeLabelRAF=0;\nfunction schedulePlaceLabels(){\n  if(placeLabelRAF)return;\n  placeLabelRAF=requestAnimationFrame(()=>{placeLabelRAF=0;renderPlaceLabels()});\n}\nfunction placePriority(name){\n  const s=String(name||'').toLowerCase();\n  if(/village|town|domain|landing|castle|forest|stable|city|stadt|dorf|spähposten|schloss|stall|reich/.test(s))return 0;\n  if(/mount|mountain|lake|island|archipelago|bridge|ruins|temple|spring|canyon|plateau|sea|berg|see|insel|brücke|ruine|tempel|quelle|hochland/.test(s))return 1;\n  return 2;\n}\nfunction renderPlaceLabels(){\n  if(!placeLabelLayer)return;\n  placeLabelLayer.innerHTML='';\n  if(!showPlaceLabels.checked)return;\n  const candidates=allMarkers().filter(m=>m.layer===currentLayer&&m.type==='location'&&m.name);\n  const zoom=view.zoom;\n  const maxPriority=zoom<1.35?0:zoom<2.05?1:2;\n  const cellPx=zoom<1.35?135:zoom<2.05?100:zoom<3.2?78:58;\n  const maxLabels=zoom<1.35?42:zoom<2.05?90:zoom<3.2?165:280;\n  const occupied=new Set();\n  const sorted=candidates.map(m=>({m,p:placePriority(m.name)})).filter(x=>x.p<=maxPriority).sort((a,b)=>a.p-b.p||String(a.m.name).length-String(b.m.name).length);\n  let shown=0;\n  for(const {m,p} of sorted){\n    const pos=coordToPct(m.x,m.y);\n    if(pos.left<0||pos.left>100||pos.top<0||pos.top>100)continue;\n    const screenX=(pos.left/100*view.baseSize*zoom)+view.x;\n    const screenY=(pos.top/100*view.baseSize*zoom)+view.y;\n    const vr=mapViewport.getBoundingClientRect();\n    if(screenX<-80||screenY<-30||screenX>vr.width+80||screenY>vr.height+30)continue;\n    const key=Math.floor(screenX/cellPx)+':'+Math.floor(screenY/cellPx);\n    if(occupied.has(key))continue;\n    occupied.add(key);\n    const el=document.createElement('button');\n    el.type='button';el.className='place-label'+(p===0?' major':'');\n    el.style.left=pos.left+'%';el.style.top=pos.top+'%';\n    el.textContent=m.name;el.title=m.name;el.setAttribute('aria-label','Ort: '+m.name);\n    el.onclick=e=>{e.stopPropagation();selectedId=m.id;render();};\n    placeLabelLayer.appendChild(el);\n    if(++shown>=maxLabels)break;\n  }\n}\n'''
js=js.replace('function renderMarkers(){',insert+'\nfunction renderMarkers(){')
js=js.replace("function render(){ $('activeLayerTitle').textContent=layerTitles[currentLayer];document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.layer===currentLayer));renderMarkers();renderDetail();renderProgress();updateDb()}", "function render(){ $('activeLayerTitle').textContent=layerTitles[currentLayer];document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.layer===currentLayer));renderMarkers();renderPlaceLabels();renderDetail();renderProgress();updateDb()}")
js=js.replace("searchInput.oninput=render;hideCompleted.onchange=render;", "searchInput.oninput=render;hideCompleted.onchange=render;showPlaceLabels.onchange=()=>{localStorage.setItem('totk.showPlaceLabels',JSON.stringify(showPlaceLabels.checked));renderPlaceLabels()};")

(p/'index.html').write_text(html,encoding='utf-8')
(p/'styles.css').write_text(css,encoding='utf-8')
(p/'app.js').write_text(js,encoding='utf-8')
(p/'README.md').write_text('''# TOTK Companion v0.8 DE\n\n## Neu in v0.8\n- Zoomabhängige Ortsnamen direkt auf Surface, Sky und Depths\n- Ortsnamen können im Marker-Menü ein-/ausgeschaltet werden\n- Labels reduzieren sich beim Herauszoomen automatisch, um Überlagerungen zu vermeiden\n- Ortslabels sind anklickbar und öffnen den zugehörigen Datensatz\n- Linkes Menü verbreitert und Filter komplett neu angeordnet\n- Lange Kategorienamen umbrechen sauber statt abgeschnitten zu werden\n- Mobile Sidebar auf maximal 360 px begrenzt und weiterhin als Drawer nutzbar\n\nHinweis: Die Ortslabels verwenden die Namen aus dem aktuell eingebetteten Datensatz. Wo die offizielle deutsche Lokalisierung bereits hinterlegt ist, wird diese verwendet.\n''',encoding='utf-8')
